pull_request_rules:
  - name: Automatic merge for Renovate and Dependabot pull requests when CI is 🟢
    conditions:
      - or:
          - author=renovate[bot]
          - author=dependabot[bot]
    actions:
      merge:
        method: rebase
