name: Lint, Test & Build

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js with last LTS version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --immutable
        env:
          HUSKY_SKIP_INSTALL: true
      - name: Lint
        run: |
          yarn lint:eslint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js with last LTS version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --immutable
        env:
          HUSKY_SKIP_INSTALL: true
      - name: Unit tests
        run: |
          yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js with last LTS version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --immutable
        env:
          HUSKY_SKIP_INSTALL: true
      - name: Build
        run: |
          yarn build
