name: Update dependencies

on:
  schedule:
  - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn up '*'
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.5.2
      with:
        commit-message: 'chore: 🔩  bump dependencies'
        branch: automatic_dependency_updates
        title: Update all dependencies
        body: An updated update of all NPM dependencies.
        delete-branch: true
